### ISSUE TITLE
Logo on navbar not centered vertically

### ISSUE THREAD

**Issue by ifreund** [roastchicken/newUniWebsite#1]
look at the pixels for proof

**Comment by roastchicken** [comment]
This is still an issue with the flexbox navbar.

**Comment by ifreund** [comment]
I suggest using the solution on the [center-logo](https://github.com/roastchicken/newUniWebsite/tree/center-logo) branch

**Comment by roastchicken** [comment]
It appears to have broken because of the div surrounding the image. The div is 4 pixels taller than the image. Setting `display: block` on the image appears to fix it.
