### ISSUE TITLE
Relative paths need to be changed to absolute paths

### ISSUE THREAD

**Issue by roastchicken** [roastchicken/newUniWebsite#11]
Absolute paths don't work on the Mac computers because Apache's root folder is their user folder, not newUniWebsite. Additionally, absolute paths won't work in production because the root folder most likely won't be newUniWebsite.

**Comment by roastchicken** [comment]
Reed pointed out that relative paths in included files will break if included from a different folder because the images will be fetched from that other folder. So what we really want to do is change all relative paths to absolute paths.

**Comment by ifreund** [comment]
Correction: by default the root for the mac apache setup is `/Library/WebServer/Documents/`
Anyhow, this can be solved fairly easily by using a virtual host.
Simply put the following in the `/etc/apache2/extra/httpd-vhosts.conf` file:
```
#Virtual Host Entry for uni.localhost
<VirtualHost *:80>
  DocumentRoot "/Users/ifreund/Sites/newUniWebsite"
  ServerName uni.localhost
  ErrorLog "/private/var/log/apache2/uni-error_log"
  CustomLog "/private/var/log/apache2/uni-access_log" common 
</VirtualHost>
```

Then, make sure the following line is uncommented in `/etc/apache2/httpd.conf`:
```
# Virtual hosts
Include /private/etc/apache2/extra/httpd-vhosts.conf
````
(this should be around line 509)

Then, add the following to `/etc/hosts`:
```
# local test server for uni website
127.0.0.1          uni.localhost
```
