### ISSUE TITLE
Navbar is fixed 1px too high

### ISSUE THREAD

**Issue by roastchicken** [roastchicken/newUniWebsite#8]
Only 63px of the navbar display after it is set to fixed. Once the page is scrolled all the way to the bottom, the full navbar is displayed.

**Comment by ifreund** [comment]
I cannot reproduce this issue, I suggest adding the following testing code to see the effect:
```
<div id="filler"></div>
```
and at the end of the file:
```
<script>
for(var i = 0; i < 100; i++) {
	document.getElementById("filler").innerHTML = document.getElementById("filler").innerHTML + "</br>" + i;
}
</script>
```

**Comment by roastchicken** [comment]
Reproduced on school computers in Chrome on Windows. Was not able to reproduce on school computers in Firefox on Windows, nor on Chrome, Safari, or Firefox on Mac OSX.

**Comment by roastchicken** [comment]
After much deliberation, Isaac and I have determined this to be a bug with Chrome on Windows and therefor isn't something we will fix.
